#!/usr/bin/env bash
# This script checks for numbers divisible by 3 and 5
for i in {1..100}
do
	if [ $((i % 5)) -eq 0 -a $((i % 3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
