#!/usr/bin/env bash
# This script displays "bad luck" for the 4th iteration, "good luck" for the 8th iterartion and "Best School" for the rest.
i="1"
while [ $i -lt 11 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
